<?php
/**
 * Small reusable template helpers shared by header/footer/page templates.
 *
 * @package Easy_Quran_Classes
 */

defined( 'ABSPATH' ) || exit;

/**
 * One icon's markup from the sprite in inc/icon-sprite.php, as a string.
 *
 * @param string $name  Icon id without the "eqc-icon-" prefix.
 * @param string $class Extra classes appended to "eqc-icon".
 */
function eqc_get_icon_html( $name, $class = '' ) {
	return sprintf(
		'<svg class="eqc-icon %s" aria-hidden="true" focusable="false"><use href="#eqc-icon-%s"></use></svg>',
		esc_attr( $class ),
		esc_attr( $name )
	);
}

/** Echo one icon — see eqc_get_icon_html(). */
function eqc_icon( $name, $class = '' ) {
	echo eqc_get_icon_html( $name, $class ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- escaped internally.
}

/**
 * Build a wa.me link from the Customizer WhatsApp number.
 *
 * @param string $prefill Optional prefilled message text.
 * @return string
 */
function eqc_whatsapp_url( $prefill = '' ) {
	$number = preg_replace( '/[^0-9]/', '', get_theme_mod( 'eqc_whatsapp_number', '10000000000' ) );
	$url    = 'https://wa.me/' . $number;
	if ( $prefill ) {
		$url .= '?text=' . rawurlencode( $prefill );
	}
	return esc_url( $url );
}

/**
 * Print the reveal-on-scroll data attributes used by assets/js/eqc.js.
 *
 * @param int $index Stagger index within the current group (0-6).
 */
function eqc_reveal_attrs( $index = 0 ) {
	$index = max( 0, min( 6, (int) $index ) );
	printf( ' data-eqc-reveal data-eqc-reveal-index="%d" ', $index );
}

/**
 * Inline one static SVG asset from the theme's assets/svg/ folder, as a
 * string — used for the divider/ornament assets generated by
 * tools/graphics/gen-ornaments.mjs (see tools/graphics/README.md). Inlined
 * rather than referenced via <img>/mask so `currentColor` follows the
 * surrounding text color (dividers sit inline in gold or cream text).
 *
 * @param string $name  Filename without the .svg extension, e.g. 'divider-section'.
 * @param string $class Extra classes appended to the root <svg>.
 * @return string
 */
function eqc_get_svg_asset( $name, $class = '' ) {
	static $cache = array();
	$cache_key = $name;
	if ( ! isset( $cache[ $cache_key ] ) ) {
		$path = get_stylesheet_directory() . '/assets/svg/' . $name . '.svg';
		$cache[ $cache_key ] = file_exists( $path ) ? file_get_contents( $path ) : ''; // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- local static theme asset.
	}
	if ( ! $cache[ $cache_key ] ) {
		return '';
	}
	// Namespace the class onto the root <svg> without a full DOM parse.
	return preg_replace( '/<svg /', '<svg class="' . esc_attr( $class ) . '" ', $cache[ $cache_key ], 1 );
}

/**
 * One of the 5 generated divider variants (see tools/graphics/README.md):
 * 'section' (main heading rule — hairline + diamonds + rosette), 'card',
 * 'dot', 'accent', 'eyebrow'.
 *
 * @param string $variant
 * @param string $class Extra classes.
 * @return string
 */
function eqc_divider_svg( $variant, $class = '' ) {
	return eqc_get_svg_asset( 'divider-' . $variant, trim( 'eqc-divider-svg ' . $class ) );
}

/**
 * The logo mark (headset + mihrab arch + open book + calligraphy — traced
 * from the client-approved Assests/Logo/Logo2.jpeg, see DESIGN.md §5),
 * inlined so `currentColor` follows the surrounding text color — one
 * asset serves both the header (dark-green text) and the footer (gold
 * text on the dark CTA panel) via CSS alone, no separate "mono" file.
 *
 * @param string $class Extra classes appended to "eqc-logo-mark".
 * @return string
 */
function eqc_logo_mark_svg( $class = '' ) {
	$svg = eqc_get_svg_asset( 'logo/eqc-logo-mark', trim( 'eqc-logo-mark ' . $class ) );
	if ( ! $svg ) {
		return '';
	}
	// The asset file carries aria-label="Easy Quran Classes". Every call site
	// pairs the mark with live text that already says the same thing (the
	// lockup below) or is purely ornamental (the footer medallion), so the
	// label would only duplicate the link name — hide the mark from
	// assistive tech at the point of use rather than in the generated asset.
	return preg_replace( '/<svg /', '<svg aria-hidden="true" focusable="false" ', $svg, 1 );
}

/**
 * The full brand lockup as a home link: the mark, "EASY QURAN" on one line,
 * and a letterspaced "CLASSES" between two short gold rules below it —
 * the two-line wordmark the client reference uses in both the header and
 * the footer (Assests/Home.jpeg, Assests/End.jpeg).
 *
 * Both lines are live text driven by the WordPress site title (the last
 * word becomes the ruled sub-line), so the brand name is still owned by
 * Settings > General and stays selectable, translatable and searchable
 * instead of being baked into an image. A single-word site title simply
 * renders without the sub-line.
 *
 * Shared by header.php and footer.php so the two can never drift apart.
 *
 * @param string $class Extra classes appended to "eqc-logo-link".
 * @return string
 */
function eqc_logo_lockup( $class = '' ) {
	$name  = trim( wp_strip_all_tags( get_bloginfo( 'name', 'display' ) ) );
	$words = $name ? preg_split( '/\s+/', $name ) : array();
	$sub   = count( $words ) > 1 ? array_pop( $words ) : '';
	$main  = implode( ' ', $words );

	// Preserve a real word separator between the two display lines so the
	// link's accessible name comes directly from its visible text.
	$html  = '<a class="' . esc_attr( trim( 'eqc-logo-link ' . $class ) ) . '" href="' . esc_url( home_url( '/' ) ) . '" rel="home">';
	$html .= eqc_logo_mark_svg();
	$html .= '<span class="eqc-logo-lockup">';
	$html .= '<span class="eqc-logo-name">' . esc_html( $main ) . '</span> ';
	if ( $sub ) {
		$html .= '<span class="eqc-logo-sub">'
			. '<span class="eqc-logo-rule" aria-hidden="true"></span>'
			. '<span class="eqc-logo-sub-text">' . esc_html( $sub ) . '</span>'
			. '<span class="eqc-logo-rule" aria-hidden="true"></span>'
			. '</span>';
	}
	$html .= '</span></a>';

	return $html;
}

/**
 * Render the shared blog-card markup for a list of WP_Post objects.
 * Used by archive.php (the real Blog page) and by the [eqc_latest_posts]
 * shortcode below, so the two never drift apart.
 *
 * @param WP_Post[] $posts
 * @return string
 */
function eqc_render_blog_cards( $posts ) {
	if ( empty( $posts ) ) {
		return '<div class="eqc-card" style="max-width:var(--eqc-content-narrow);margin-inline:auto;text-align:center;"><p>' . esc_html__( 'No posts have been published yet. Please check back soon.', 'easy-quran-classes' ) . '</p></div>';
	}

	$html = '<div class="eqc-grid eqc-grid--blog">';
	$i    = 0;
	foreach ( $posts as $post ) {
		$i++;
		$permalink = get_permalink( $post );
		$cats      = get_the_category( $post->ID );
		$thumb     = has_post_thumbnail( $post ) ? get_the_post_thumbnail( $post, 'eqc-blog-card' ) : '';

		// Blogs.jpeg puts a white date chip (calendar icon, day, month) over the
		// image's top-left corner, and the category as plain gold caps above the
		// title - not a ribbon on the image.
		$chip = '<span class="eqc-blog-date">' . eqc_get_icon_html( 'calendar' )
			. '<span class="eqc-blog-date__day">' . esc_html( get_the_date( 'j', $post ) ) . '</span>'
			. '<span class="eqc-blog-date__mon">' . esc_html( strtoupper( get_the_date( 'M', $post ) ) ) . '</span></span>';
		$category = ! empty( $cats ) ? '<span class="eqc-blog-category">' . esc_html( $cats[0]->name ) . '</span>' : '';

		$html .= '<article class="eqc-card eqc-card--blog" data-eqc-reveal data-eqc-reveal-index="' . min( $i, 3 ) . '">';
		// aria-hidden + tabindex -1: the title and "Read More" links below already
		// point here, so exposing the image as a third unnamed link would add
		// a nameless tab stop for no gain.
		$html .= '<a class="eqc-blog-media" href="' . esc_url( $permalink ) . '" tabindex="-1" aria-hidden="true">' . $thumb . '</a>' . $chip;
		$html .= '<div class="eqc-blog-body">';
		$html .= $category;
		$html .= '<h3><a href="' . esc_url( $permalink ) . '" style="text-decoration:none;color:inherit;">' . esc_html( get_the_title( $post ) ) . '</a></h3>';
		$html .= '<p class="eqc-blog-excerpt">' . esc_html( wp_trim_words( get_the_excerpt( $post ), 18 ) ) . '</p>';
		/* translators: %s: post title, read by screen readers only — the visible link text stays the short "Read More". */
		$read_more_label = sprintf( __( 'Read more: %s', 'easy-quran-classes' ), get_the_title( $post ) );
		$html           .= '<a class="eqc-read-more" href="' . esc_url( $permalink ) . '" aria-label="' . esc_attr( $read_more_label ) . '">' . esc_html__( 'Read More', 'easy-quran-classes' ) . '<span class="eqc-read-more__disc" aria-hidden="true">' . eqc_get_icon_html( 'chevrons-right' ) . '</span>' . '</a>';
		$html .= '</div></article>';
	}
	$html .= '</div>';
	return $html;
}

/**
 * [eqc_latest_posts count="3"] — the site's only "dynamic Posts" mechanism
 * for Elementor Free (which ships no query/Posts widget). Registered here
 * instead of a plugin: it is a three-line WP_Query wrapped around the same
 * card markup archive.php already uses, always reflects the live Posts
 * table, and an admin drops it anywhere via Elementor's Shortcode widget.
 */
function eqc_latest_posts_shortcode( $atts ) {
	$atts  = shortcode_atts( array( 'count' => 3 ), $atts );
	$query = new WP_Query(
		array(
			'post_type'      => 'post',
			'post_status'    => 'publish',
			'posts_per_page' => (int) $atts['count'],
			'ignore_sticky_posts' => true,
		)
	);
	$html = eqc_render_blog_cards( $query->posts );
	wp_reset_postdata();
	return $html;
}
add_shortcode( 'eqc_latest_posts', 'eqc_latest_posts_shortcode' );

/**
 * Fetch the Media Library URL for one of the placeholder images seeded
 * during the build, by its recognizable filename fragment. Falls back to
 * an empty string (never a hardcoded absolute path) if not found, so
 * templates degrade gracefully if media is re-imported with new IDs.
 *
 * Matches the `_wp_attached_file` postmeta (the real source filename), not
 * `post_name` — `wp media import --title="..."` derives post_name from the
 * given title, not the filename, so a post_name match silently misses (see
 * eqc_media_id() in tools/elementor-helpers.php, which hit the exact same
 * bug; this function went uncalled until the footer avatar-stack needed
 * it, so it was never caught until now).
 *
 * @param string $slug_fragment e.g. 'hero-online-quran-class'.
 * @return array{0:string,1:string} [url, alt]
 */
function eqc_seed_image( $slug_fragment ) {
	global $wpdb;
	static $cache = array();
	if ( isset( $cache[ $slug_fragment ] ) ) {
		return $cache[ $slug_fragment ];
	}
	$id     = $wpdb->get_var( $wpdb->prepare( "SELECT post_id FROM {$wpdb->postmeta} WHERE meta_key = '_wp_attached_file' AND meta_value LIKE %s ORDER BY post_id DESC LIMIT 1", '%' . $wpdb->esc_like( $slug_fragment ) . '%' ) );
	$result = array( '', '' );
	if ( $id ) {
		$result = array( wp_get_attachment_url( (int) $id ), get_post_meta( (int) $id, '_wp_attachment_image_alt', true ) );
	}
	$cache[ $slug_fragment ] = $result;
	return $result;
}
